### PR TITLE
LIMS-1627 Pricing per Analysis Profile

### PR DESCRIPTION
**Pull request by Espurna**
https://jira.bikalabs.com/browse/LIMS-1627

- Analysis request add form allows more than one analysis profile per analysis reuqest.
- Client's Bulk Discount Price used to compute prices on analysis request add form.
- Member discount and bulk discount used to computed the invoices.
- If a profile has its own price, it'll be used to compute the prices on the analysis request add form and in the invoice

### CODE REVIEW

**Comment by Espurna** [comment]
I'm working on a simple test

**Comment by Espurna** [comment]
I cannot run these tests because "Enable autologin as" doesn't have declaration anywhere, or I don't see it... @rockfruit ?

**Comment by lemoene** [comment]
Does @rockfruit cut it now - it seems like it, or do we still have to use [~rockfruit]? Anyhows, you might've missed @Espurna's  message

**Comment by rockfruit** [comment]
Slow reply....

I think it's this line:

    Library         Remote  ${PLONEURL}/RobotRemote

In my robots though, I have usually an almost-identical settings block in all:

    Library         BuiltIn
    Library         Selenium2Library  timeout=5  implicit_wait=0.2
    Library         String
    Resource        keywords.txt
    Library         bika.lims.testing.Keywords
    Resource        plone/app/robotframework/selenium.robot
    Library         Remote  ${PLONEURL}/RobotRemote
    Variables       plone/app/testing/interfaces.py
    Variables       bika/lims/tests/variables.py
    Suite Setup     Start browser
    Suite Teardown  Close All Browsers
    Library          DebugLibrary

**Comment by rockfruit** [comment]
This is a great PR, functionality that we've missed for a long time!

**Comment by rockfruit** [comment]
The tests work here (enable autologin as is found correctly).  Though there are failures; For one, I don't think you can have '-' in robot variable names

**Comment by xispa** [comment]
Indeed @rockfruit . Keep in mind that equigerminal fork still uses 3.1.8 and wip is the working branch. This is because bika.health's AR Add form hasn't been refactored yet to be compatible with 3.1.9. This will be done on August, a month before the release sprint. Nevertheless, we create specific branchs for doing PR to 3.1.9 if required and do cherrypicks to wip.

**Comment by Espurna** [comment]
Thanks @rockfruit, I mean unselect. But I cannot run the test, I thing I'm missing some robot packages... I added "robotframework-debug library" and "robotremoteserver" on my buildout file, but I have this error:

 [ ERROR ] Error in file '/home/pau/dev/equigerminal/zinstance/src/bika.lims/bika/lims/tests/test_AnalysisRequest_add.robot': Calling dynamic method 'get_keyword_names' failed: Connecting remote server at http://localhost:55001/plone/RobotRemote failed: Connection refused

And I guess that error causes my "No keyword with name 'Enable autologin as' found." error.

When you have time, would be you so kind to send me your buildout please?

**Comment by rockfruit** [comment]
I'm using the unified installer, first I rename "buildout.cfg" to "buildout-original.cfg", then I create a new buildout.cfg.  This is the whole file as I am using it now:

    [buildout]
    
    # buildout-original.cfg is the Plone 4.3 unified-installer file.
    extends =
        buildout-original.cfg
    
    zeo-address = 8100
    client1-address = 8080
    client2-address = 8081
    
    effective-user = campbell
    buildout-user = campbell
    user=admin:adminsecret
    
    need-sudo = no
    var-dir=${buildout:directory}/var
    backups-dir=${buildout:directory}/backups
    deprecation-warnings = on
    verbose-security = on
    
    eggs =
        bika.lims
    #    bika.health
    #    graphite.theme
    #    bika.wine
    #    bika.bbk
    #    bika.health
    #    bika.vet
    #    bika.labsanmartin
    #    bika.geochem
    #    SESAR-Web-Services-Library
    #    bika.custom
    #    plone.app.debugtoolbar
    #    sauna.reload
        pudb
        i18ndude
    #    Products.PDBDebugmode
        test
        robot
        zest.releaser
    
    develop +=
        /home/campbell/repos/bika.lims
    #    /home/campbell/repos/bika.wine
    #    /home/campbell/repos/bika.bbk
    #    /home/campbell/repos/bika.health
    #    /home/campbell/repos/bika.veterinary
    #    /home/campbell/repos/bika.labsanmartin
    #    /home/campbell/repos/bika.geochem
    #    /home/campbell/repos/bika.custom
    #    /home/campbell/repos/graphite.theme
    
    parts =
    #    filestorage
        zeoserver
        client1
        client2
        backup
        zopepy
        unifiedinstaller
        zopeskel
        omelette
        i18ndude
        test
        robot
    
    zcml =
    
    [filestorage]
    recipe = collective.recipe.filestorage
    parts =
        develop
        next
    location = var/filestorage/%(fs_part_name)s/Data.fs
    blob-storage = var/blobstorage/%(fs_part_name)s
    zeo-client-cache-size = 250MB
    zodb-cache-size = 1000
    zodb-mountpoint = /%(fs_part_name)s
    
    [zeoserver]
    <= zeoserver_base
    recipe = plone.recipe.zeoserver
    zeo-address = 127.0.0.1:${buildout:zeo-address}
    zserver-threads = 1
    
    [client1]
    <= client_base
    recipe = plone.recipe.zope2instance
    zeo-address = ${zeoserver:zeo-address}
    http-address = ${buildout:client1-address}
    resources = ${buildout:directory}/resources
    locales = ${buildout:directory}/locales
    http-fast-listen = off
    
    [client2]
    <= client_base
    recipe = plone.recipe.zope2instance
    zeo-address = ${zeoserver:zeo-address}
    http-address = ${buildout:client2-address}
    resources = ${buildout:directory}/resources
    locales = ${buildout:directory}/locales
    http-fast-listen = off
    
    [versions]
    Cheetah = 2.2.1
    plone.recipe.command = 1.1
    plone.recipe.precompiler = 0.6
    plone.recipe.unifiedinstaller = 4.3.1
    Products.DocFinderTab = 1.0.5
    ZopeSkel = 2.21.2
    collective.recipe.backup = 2.14
    zopeskel.dexterity = 1.5.3
    zopeskekel.dexterity = 1.5.3
    zopeskel.diazotheme = 1.1
    
    [omelette]
    recipe = collective.recipe.omelette
    eggs = ${buildout:eggs}
    
    [i18ndude]
    unzip = true
    recipe = zc.recipe.egg
    eggs = i18ndude
    
    [zopeskel]
    # installs paster and Zopeskel
    recipe = zc.recipe.egg
    eggs =
        ZopeSkel
        Paste
        PasteDeploy
        PasteScript
        zopeskel.diazotheme
        zopeskel.dexterity
        zest.releaser
        ${buildout:eggs}
    
    [test]
    recipe = zc.recipe.testrunner
    defaults = ['--auto-color', '--auto-progress']
    eggs =
        bika.lims [test]
        plone.app.testing
    
    [robot]
    recipe = zc.recipe.egg
    eggs =
        Pillow
        plone.app.robotframework

**Comment by Espurna** [comment]
pau@mendel:~/dev/equigerminal/zinstance$ bin/test -m bika.lims -t test_AnalysisRequest_add.robot
Running bika.lims.testing.BikaTestingLayer:Robot tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.155 seconds.
  Set up plone.app.testing.layers.PloneFixture in 5.062 seconds.
  Set up bika.lims.testing.BikaTestLayer in 43.351 seconds.
  Set up plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.012 seconds.
  Set up plone.testing.z2.ZServer in 0.502 seconds.
  Set up bika.lims.testing.BikaTestingLayer:Robot in 0.000 seconds.
  Running:
                
  Ran 8 tests with 0 failures and 0 errors in 1 minutes 32.889 seconds.
Tearing down left over layers:
  Tear down bika.lims.testing.BikaTestingLayer:Robot in 0.000 seconds.
  Tear down plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.004 seconds.
  Tear down plone.testing.z2.ZServer in 5.222 seconds.
  Tear down bika.lims.testing.BikaTestLayer in 0.017 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.059 seconds.
  Tear down plone.testing.z2.Startup in 0.005 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.008 seconds.
pau@mendel:~/dev/equigerminal/zinstance$ 


LOOK!
Since some Bika dependencies have been upgraded, you should add (change) the following lines in your buildout.cfg:
extends =
    base.cfg
#    versions.cfg
    http://dist.plone.org/release/4.3-latest/versions.cfg

# If you change your Plone version, you'll also need to update
# the repository link below.
find-links +=
    http://dist.plone.org/release/4.3.6

[...]

[robot]
recipe = zc.recipe.egg
eggs =
    Pillow
    ${test:eggs}
    plone.app.robotframework
    Products.PloneTestCase
    plone.resource
    plone.app.textfield
    robotframework-debuglibrary

[test]
recipe = zc.recipe.testrunner
eggs =
    Pillow
    bika.lims
    plone.app.robotframework
    Products.PloneTestCase
    plone.resource
    plone.app.textfield
    robotframework-debuglibrary

**Pull request merged**
