### PR TITLE
System Dashboard

### PR DESCRIPTION
**Pull request by xispa**
New system dashboard view for LabManagers and Admins

dashboard

### CODE REVIEW

**Comment by Espurna** [comment]
+1

**Comment by lemoene** [comment]
awesome!

**Comment by rockfruit** [comment]
perfecto

**Comment by shamut** [comment]
Thank Jordi, this is awesome. A few comments from me:
1) Can the dash board show by analysis, this will be important for managers to know the exact analysis in question.
2) Can one be able to expand using a hyperlink. For example, if i see that there are 54 results pending publishing, will i be able to expand and see the exact results

Once again, this is a job well done 
Tendai

**Comment by xispa** [comment]
Hi Tendai,

> 1) Can the dash board show by analysis, this will be important for managers to know the exact analysis in question.

Yes, a section for analyses can be added, as well as other data you might find useful. This dashboard is a first approach and can be improved with new sections and functionalities. On a mid-term, I'd like to give to the user the option to configure the 'sections' to be displayed by default. Created an issue in the tracker: [LIMS-1968 Add Analyses section in the Dashboard](https://jira.bikalabs.com/browse/LIMS-1968)

> 2) Can one be able to expand using a hyperlink. For example, if i see that there are 54 results pending publishing, will i be able to expand and see the exact results

Already done. Right now, each 'numbered-pie-chart' is a link to a view where the objects with that status are listed.

**Comment by shamut** [comment]
Jordi
Good to hear that, glad this can be expanded to the actual lists. I think it will be great to do it by analysis and analysis category as per current architecture. You know i also prefer it by department :)

**Pull request merged**
